import { createFileRoute } from '@tanstack/react-router'
import { useState } from 'react'
import { CalendarDays, DollarSign, Users, Pencil, Trash2, Plus } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { services as initialServices, offers as initialOffers } from '@/data/salon'
export const Route=createFileRoute('/admin')({head:()=>({meta:[{title:'Salon Dashboard | GlowNest'},{name:'description',content:'GlowNest appointment, service and offer management dashboard.'},{property:'og:title',content:'Salon Dashboard | GlowNest'},{property:'og:description',content:'Manage GlowNest appointments and salon offerings.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Admin})
const initialAppointments=[{id:1,client:'Olivia Chen',service:'Balayage & Gloss',time:'Sep 24 · 10:00',status:'Confirmed'},{id:2,client:'Sofia Reed',service:'Hydra-Glow Facial',time:'Sep 24 · 13:30',status:'Pending'},{id:3,client:'Maya Patel',service:'The Bridal Suite',time:'Sep 25 · 09:00',status:'Confirmed'}]
function Admin(){const [appointments,setAppointments]=useState(initialAppointments);const [services,setServices]=useState(initialServices);const [offers,setOffers]=useState(initialOffers);const [newService,setNewService]=useState('');return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><p className="eyebrow">Owner workspace</p><h1 className="mt-2 font-display text-5xl">Good afternoon.</h1><div className="mt-8 grid gap-4 sm:grid-cols-3"><Metric icon={<CalendarDays/>} label="Appointments" value="12 today"/><Metric icon={<Users/>} label="Guests" value="286 total"/><Metric icon={<DollarSign/>} label="Booked value" value="$2,840"/></div><div className="mt-8 grid gap-5 lg:grid-cols-[1.35fr_1fr]"><section className="glass rounded-2xl p-5"><h2 className="font-display text-2xl">Appointments</h2><div className="mt-4 overflow-x-auto"><table className="w-full min-w-[560px] text-left text-sm"><thead className="text-xs text-muted-foreground"><tr><th className="py-3">Customer</th><th>Service</th><th>Date</th><th>Status</th></tr></thead><tbody>{appointments.map(a=><tr key={a.id} className="border-t border-border"><td className="py-4 font-medium">{a.client}</td><td>{a.service}</td><td>{a.time}</td><td><select value={a.status} onChange={e=>setAppointments(x=>x.map(i=>i.id===a.id?{...i,status:e.target.value}:i))} className="field h-9 w-28"><option>Pending</option><option>Confirmed</option><option>Completed</option><option>Cancelled</option></select></td></tr>)}</tbody></table></div></section><section className="glass rounded-2xl p-5"><h2 className="font-display text-2xl">Customer details</h2><div className="mt-4 space-y-3">{appointments.map(a=><div key={a.id} className="rounded-xl bg-secondary/70 p-4"><strong className="text-sm">{a.client}</strong><p className="mt-1 text-xs text-muted-foreground">(555) 010-{1000+a.id} · client@example.com</p></div>)}</div></section></div><div className="mt-5 grid gap-5 lg:grid-cols-2"><Manage title="Services" items={services.map(s=>({name:s.name,price:s.price}))} onDelete={name=>setServices(x=>x.filter(i=>i.name!==name))} extra={<form className="mt-4 flex gap-2" onSubmit={e=>{e.preventDefault();if(newService.trim()){setServices(x=>[...x,{category:'New',name:newService,description:'New salon service',duration:'60 min',price:100}]);setNewService('')}}}><Input value={newService} onChange={e=>setNewService(e.target.value)} placeholder="New service name"/><Button size="icon" aria-label="Add service"><Plus/></Button></form>}/><Manage title="Offers" items={offers.map(o=>({name:o.name,price:o.price}))} onDelete={name=>setOffers(x=>x.filter(i=>i.name!==name))}/></div></main>}
function Metric({icon,label,value}:{icon:React.ReactNode;label:string;value:string}){return <div className="glass rounded-2xl p-5"><div className="text-primary">{icon}</div><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="font-display text-2xl">{value}</p></div>}
function Manage({title,items,onDelete,extra}:{title:string;items:{name:string;price:number}[];onDelete:(n:string)=>void;extra?:React.ReactNode}){return <section className="glass rounded-2xl p-5"><h2 className="font-display text-2xl">Manage {title.toLowerCase()}</h2><div className="mt-4 space-y-2">{items.map(i=><div key={i.name} className="flex items-center gap-2 rounded-xl bg-secondary/60 p-3"><span className="min-w-0 flex-1 truncate text-sm">{i.name}</span><Input aria-label={`${i.name} price`} type="number" defaultValue={i.price} className="h-8 w-20"/><Button variant="ghost" size="icon" aria-label={`Edit ${i.name}`}><Pencil/></Button><Button variant="ghost" size="icon" aria-label={`Delete ${i.name}`} onClick={()=>onDelete(i.name)}><Trash2/></Button></div>)}</div>{extra}</section>}
