import { createFileRoute, Link } from '@tanstack/react-router'
import { useState, type FormEvent } from 'react'
import { CheckCircle2 } from 'lucide-react'
import { PageIntro } from '@/components/SiteLayout'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
import { services, team } from '@/data/salon'
export const Route=createFileRoute('/booking')({validateSearch:(s:Record<string,unknown>)=>({service:typeof s.service==='string'?s.service:''}),head:()=>({meta:[{title:'Book an Appointment | GlowNest'},{name:'description',content:'Request your GlowNest salon appointment online.'},{property:'og:title',content:'Book an Appointment | GlowNest'},{property:'og:description',content:'Choose your treatment, stylist, date and preferred time.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Booking})
function Booking(){const {service}=Route.useSearch();const [done,setDone]=useState(false);function submit(e:FormEvent){e.preventDefault();setDone(true);window.scrollTo({top:0,behavior:'smooth'})}if(done)return <main className="mx-auto grid min-h-[70vh] max-w-2xl place-items-center px-4"><div className="glass rounded-2xl p-10 text-center"><CheckCircle2 className="mx-auto size-12 text-primary"/><p className="eyebrow mt-5">Request received</p><h1 className="mt-2 font-display text-4xl">Your glow time is almost here.</h1><p className="mt-4 text-muted-foreground">Thank you. Our concierge will call or email shortly to confirm your appointment details.</p><Button asChild variant="secondary" className="mt-7 rounded-full"><Link to="/">Return home</Link></Button></div></main>;return <main><PageIntro eyebrow="Appointment request" title="Reserve time for yourself." text="Share your preferred details and our concierge will confirm availability with you personally."/><form onSubmit={submit} className="glass mx-auto grid max-w-3xl gap-5 rounded-2xl p-6 sm:grid-cols-2 sm:p-8"><Field label="Name"><Input required name="name" placeholder="Your full name"/></Field><Field label="Phone number"><Input required name="phone" type="tel" placeholder="(555) 000-0000"/></Field><Field label="Email"><Input required name="email" type="email" placeholder="you@example.com"/></Field><Field label="Service"><select required name="service" defaultValue={service} className="field"><option value="">Select a service</option>{services.map(s=><option key={s.name}>{s.name}</option>)}</select></Field><Field label="Preferred stylist"><select required name="stylist" className="field"><option value="">Select a stylist</option><option>First available</option>{team.map(t=><option key={t.name}>{t.name}</option>)}</select></Field><Field label="Date"><Input required name="date" type="date" min="2026-09-23"/></Field><Field label="Time"><Input required name="time" type="time" min="09:00" max="19:00"/></Field><div className="sm:col-span-2"><Label htmlFor="message">Additional message</Label><Textarea id="message" name="message" className="mt-2" placeholder="Tell us about allergies, preferences or the occasion."/></div><Button type="submit" className="rounded-full sm:col-span-2">Request Appointment</Button></form></main>}
function Field({label,children}:{label:string;children:React.ReactNode}){return <div><Label>{label}</Label><div className="mt-2">{children}</div></div>}
