import { createFileRoute } from '@tanstack/react-router'
import { useState, type FormEvent } from 'react'
import { Mail, MapPin, Phone } from 'lucide-react'
import { PageIntro } from '@/components/SiteLayout'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Label } from '@/components/ui/label'
export const Route=createFileRoute('/contact')({head:()=>({meta:[{title:'Contact GlowNest Beauty & Wellness'},{name:'description',content:'Contact GlowNest, find our opening hours and plan your salon visit.'},{property:'og:title',content:'Contact GlowNest Beauty & Wellness'},{property:'og:description',content:'Visit our atelier or send the GlowNest team a message.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Contact})
function Contact(){const [sent,setSent]=useState(false);function submit(e:FormEvent){e.preventDefault();setSent(true)}return <main><PageIntro eyebrow="Visit the atelier" title="We would love to welcome you." text="Questions, special occasions or a little help choosing? Our concierge is here."/><div className="mx-auto grid max-w-6xl gap-5 px-4 sm:px-6 lg:grid-cols-2"><section className="glass rounded-2xl p-7"><div className="space-y-5 text-sm"><p className="flex gap-3"><MapPin className="size-5 text-primary"/>214 Linden Row, Suite 2<br/>Rosewood District</p><p className="flex gap-3"><Phone className="size-5 text-primary"/>(555) 018-4470</p><p className="flex gap-3"><Mail className="size-5 text-primary"/>hello@glownest.studio</p></div><div className="mt-8 border-t border-border pt-6"><h2 className="font-display text-2xl">Opening hours</h2><p className="mt-3 text-sm text-muted-foreground">Tuesday–Saturday · 9am–7pm<br/>Sunday · 10am–4pm<br/>Monday · Closed</p></div><div className="map mt-8 grid aspect-[16/7] place-items-center rounded-xl"><div className="rounded-full bg-background px-4 py-2 text-xs shadow">GlowNest · Linden Row</div></div></section><form onSubmit={submit} className="glass rounded-2xl p-7"><h2 className="font-display text-3xl">Send a note</h2>{sent?<p className="mt-5 rounded-xl bg-secondary p-4 text-sm">Thank you. We’ll be in touch within one business day.</p>:<div className="mt-6 space-y-4"><div><Label htmlFor="contact-name">Name</Label><Input id="contact-name" required className="mt-2"/></div><div><Label htmlFor="contact-email">Email</Label><Input id="contact-email" type="email" required className="mt-2"/></div><div><Label htmlFor="contact-message">Message</Label><Textarea id="contact-message" required className="mt-2 min-h-32"/></div><Button className="w-full rounded-full">Send Message</Button></div>}</form></div></main>}
