import { createFileRoute } from '@tanstack/react-router'
import { useEffect, useState } from 'react'
import { X } from 'lucide-react'
import { PageIntro } from '@/components/SiteLayout'
import { Button } from '@/components/ui/button'
import gallery from '@/assets/glownest-gallery.jpg'
import { galleryItems } from '@/data/salon'
export const Route=createFileRoute('/gallery')({head:()=>({meta:[{title:'Salon Gallery | GlowNest'},{name:'description',content:'Explore GlowNest salon interiors, hair, makeup, nails, spa and bridal work.'},{property:'og:title',content:'Salon Gallery | GlowNest'},{property:'og:description',content:'A closer look at the GlowNest atelier and our work.'},{property:'og:type',content:'website'},{name:'twitter:card',content:'summary_large_image'}]}),component:Gallery})
function Gallery(){const [selected,setSelected]=useState<number|null>(null);useEffect(()=>{const close=(e:KeyboardEvent)=>e.key==='Escape'&&setSelected(null);document.addEventListener('keydown',close);return()=>document.removeEventListener('keydown',close)},[]);return <main><PageIntro eyebrow="The lookbook" title="Inside the atelier." text="A closer look at our space, our rituals and the details we love."/><div className="mx-auto grid max-w-6xl grid-cols-2 gap-3 px-4 sm:px-6 lg:grid-cols-3">{galleryItems.map((g,i)=><button key={g.name} onClick={()=>setSelected(i)} className="group relative aspect-square overflow-hidden rounded-2xl text-left" aria-label={`Open ${g.name} image`}><div className="gallery-sprite h-full w-full transition-transform duration-700 group-hover:scale-105" style={{backgroundImage:`url(${gallery})`,backgroundPosition:g.position}}/><span className="absolute inset-x-3 bottom-3 rounded-lg bg-background/80 px-3 py-2 text-xs backdrop-blur">{g.name}</span></button>)}</div>{selected!==null&&<div className="fixed inset-0 z-[70] grid place-items-center bg-foreground/85 p-4" onClick={()=>setSelected(null)} role="dialog" aria-modal="true"><Button variant="secondary" size="icon" className="absolute right-5 top-5" onClick={()=>setSelected(null)} aria-label="Close"><X/></Button><div className="gallery-sprite aspect-square w-full max-w-2xl rounded-2xl" style={{backgroundImage:`url(${gallery})`,backgroundPosition:galleryItems[selected].position}}/></div>}</main>}
